import express from 'express';
import crypto from 'node:crypto';
import pg from 'pg';
const { Pool } = pg;

const app=express(); app.disable('x-powered-by');
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');next()});
app.use(express.json({limit:'1mb'})); 
const rate=new Map();
function rateLimit(req,res,next){const key=(req.ip||'unknown')+'|'+req.path,now=Date.now();let x=rate.get(key);if(!x||now-x.t>60000)x={t:now,n:0};x.n++;rate.set(key,x);if(x.n>120)return res.status(429).json({error:'Rate limit exceeded'});next()}
app.use('/api',rateLimit);

const BASE=process.env.BINANCE_BASE_URL||'https://fapi.binance.com', WS_BASE=process.env.BINANCE_WS_URL||'wss://fstream.binance.com';
const LIVE=process.env.ENABLE_LIVE_TRADING==='true', MAXLEV=Number(process.env.MAX_LEVERAGE||20), MAXRISK=Number(process.env.MAX_RISK_PCT||2), MAX_DD=Number(process.env.MAX_DAILY_LOSS_PCT||5);
const ALLOWED=new Set((process.env.ALLOWED_SYMBOLS||'BTCUSDT,ETHUSDT,BNBUSDT,SOLUSDT,XRPUSDT,DOGEUSDT,ADAUSDT').split(',').map(x=>x.trim().toUpperCase()));
const MASTER=process.env.MASTER_KEY||'', DATABASE_URL=process.env.DATABASE_URL||'';
if(!DATABASE_URL) console.warn('DATABASE_URL is not configured');
const pool=new Pool({connectionString:DATABASE_URL,ssl:process.env.PGSSL==='disable'?false:{rejectUnauthorized:false},max:Number(process.env.PG_POOL_MAX||10),idleTimeoutMillis:30000,connectionTimeoutMillis:10000});
const SESSION_TTL=Number(process.env.SESSION_TTL_SEC||28800)*1000;
let killSwitch=false, dayState={date:new Date().toISOString().slice(0,10),equityStart:0}, KEY='', SECRET='';

async function q(sql,params=[]){return (await pool.query(sql,params)).rows}
async function exec(sql,params=[]){await pool.query(sql,params)}
async function initDb(){await exec(`CREATE TABLE IF NOT EXISTS trades(id TEXT PRIMARY KEY,symbol TEXT,side TEXT,entry DOUBLE PRECISION,exit DOUBLE PRECISION,qty DOUBLE PRECISION,pnl DOUBLE PRECISION DEFAULT 0,fee DOUBLE PRECISION DEFAULT 0,funding DOUBLE PRECISION DEFAULT 0,opened_at BIGINT,closed_at BIGINT,reason TEXT,setup TEXT,status TEXT DEFAULT 'OPEN',meta JSONB);CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,symbol TEXT,client_order_id TEXT,exchange_order_id TEXT,side TEXT,type TEXT,qty DOUBLE PRECISION,price DOUBLE PRECISION,status TEXT,reduce_only BOOLEAN DEFAULT FALSE,created_at BIGINT,updated_at BIGINT,raw JSONB);CREATE TABLE IF NOT EXISTS journal(id TEXT PRIMARY KEY,trade_id TEXT,note TEXT,tags TEXT,created_at BIGINT);CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY,action TEXT,actor TEXT,detail TEXT,created_at BIGINT);CREATE TABLE IF NOT EXISTS settings(k TEXT PRIMARY KEY,v TEXT);CREATE TABLE IF NOT EXISTS credentials(id INTEGER PRIMARY KEY CHECK(id=1),api_key_enc TEXT,api_secret_enc TEXT,totp_enc TEXT);CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY CHECK(id=1),username TEXT UNIQUE,salt TEXT,password_hash TEXT,created_at BIGINT);CREATE INDEX IF NOT EXISTS idx_trades_opened ON trades(opened_at DESC);CREATE INDEX IF NOT EXISTS idx_audit_created ON audit(created_at DESC);`)}
let dbReady=false, dbInitPromise=null;
async function ensureDb(){if(dbReady)return;if(!dbInitPromise)dbInitPromise=initDb().then(()=>{dbReady=true}).catch(e=>{dbInitPromise=null;throw e});await dbInitPromise}
app.use('/api',async(req,res,next)=>{try{await ensureDb();next()}catch(e){res.status(503).json({error:'Database initialization failed',detail:e.message})}});
async function audit(action,detail='',actor='system'){try{await exec('INSERT INTO audit(id,action,actor,detail,created_at) VALUES($1,$2,$3,$4,$5)',[crypto.randomUUID(),action,actor,detail,Date.now()])}catch(e){console.error('audit',e.message)}}
function passwordHash(password,salt=crypto.randomBytes(16).toString('hex')){const h=crypto.scryptSync(String(password),salt,64,{N:16384,r:8,p:1});return {salt,hash:h.toString('hex')}}
function makeToken(user){if(!MASTER)throw Error('MASTER_KEY is not configured');const payload=Buffer.from(JSON.stringify({u:user,exp:Date.now()+SESSION_TTL})).toString('base64url');const mac=crypto.createHmac('sha256',MASTER).update(payload).digest('base64url');return payload+'.'+mac}
function verifyToken(token){try{const [payload,mac]=String(token||'').split('.');if(!payload||!mac)return null;const expected=crypto.createHmac('sha256',MASTER).update(payload).digest('base64url');if(!crypto.timingSafeEqual(Buffer.from(mac),Buffer.from(expected)))return null;const p=JSON.parse(Buffer.from(payload,'base64url').toString());return p.exp>Date.now()?p.u:null}catch{return null}}
function auth(req,res,next){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const user=verifyToken(token);if(!user)return res.status(401).json({error:'Authentication required'});req.user=user;next()}
function optionalAuth(req){return verifyToken(String(req.headers.authorization||'').replace(/^Bearer\s+/i,''))}
function requireMaster(req,res,next){if(!MASTER)return res.status(503).json({error:'MASTER_KEY is not configured'});next()}
function enc(s){if(!MASTER)throw Error('MASTER_KEY is required');const iv=crypto.randomBytes(12),k=crypto.createHash('sha256').update(MASTER).digest(),c=crypto.createCipheriv('aes-256-gcm',k,iv),out=Buffer.concat([c.update(String(s),'utf8'),c.final()]);return `${iv.toString('base64')}.${c.getAuthTag().toString('base64')}.${out.toString('base64')}`}
function dec(v){const [iv,tag,data]=String(v).split('.'),k=crypto.createHash('sha256').update(MASTER).digest(),d=crypto.createDecipheriv('aes-256-gcm',k,Buffer.from(iv,'base64'));d.setAuthTag(Buffer.from(tag,'base64'));return Buffer.concat([d.update(Buffer.from(data,'base64')),d.final()]).toString()}
async function loadCredentials(){try{const r=(await q('SELECT api_key_enc,api_secret_enc FROM credentials WHERE id=1'))[0];KEY=r?.api_key_enc?dec(r.api_key_enc):'';SECRET=r?.api_secret_enc?dec(r.api_secret_enc):''}catch{KEY='';SECRET=''}}
function sym(s){s=String(s||'').toUpperCase();if(!ALLOWED.has(s))throw Error('Symbol not allowed');return s}
function sig(qs){return crypto.createHmac('sha256',SECRET).update(qs).digest('hex')}
async function binance(path,p={},method='GET',signed=false){if(signed)await loadCredentials();const x={...p};if(signed){if(!KEY||!SECRET)throw Error('API credentials not configured');x.timestamp=Date.now();x.recvWindow=5000}const qs=new URLSearchParams(Object.entries(x).filter(([,v])=>v!==undefined&&v!==null).map(([k,v])=>[k,String(v)])).toString(),body=signed?`${qs}&signature=${sig(qs)}`:qs,url=BASE+path+(['GET','DELETE'].includes(method)&&body?`?${body}`:'');const r=await fetch(url,{method,headers:{'X-MBX-APIKEY':KEY,'Content-Type':'application/x-www-form-urlencoded'},body:['POST','PUT'].includes(method)?body:undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.msg||`HTTP ${r.status}`);return d}
function riskCalc({entry,stopLoss,capital,riskPct,leverage}){const E=+entry,SL=+stopLoss,C=+capital,R=+riskPct,L=Math.min(+leverage,MAXLEV);if(![E,SL,C,R,L].every(Number.isFinite)||E<=0||SL<=0||C<=0||R<=0)throw Error('Invalid risk input');if(R>MAXRISK)throw Error(`Risk capped at ${MAXRISK}%`);const loss=Math.abs(E-SL),riskUsd=C*R/100,qty=Math.min(riskUsd/loss,C*L/E);return {quantity:qty,notional:qty*E,margin:qty*E/L,riskUsd,estimatedLoss:qty*loss,leverage:L}}
function decodeBase32(input){const a='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='',out=[];for(const ch of String(input).replace(/=+$/,'').toUpperCase().replace(/\s/g,'')){const i=a.indexOf(ch);if(i<0)throw Error('Invalid TOTP secret');bits+=i.toString(2).padStart(5,'0');while(bits.length>=8){out.push(parseInt(bits.slice(0,8),2));bits=bits.slice(8)}}return Buffer.from(out)}
function totp(secret,time=Math.floor(Date.now()/1000),step=30,digits=6){const key=decodeBase32(secret),b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(Math.floor(time/step)));const h=crypto.createHmac('sha1',key).update(b).digest(),o=h[h.length-1]&15;return String((h.readUInt32BE(o)&0x7fffffff)%10**digits).padStart(digits,'0')}
function base32(buf){let bits='',out='';for(const b of buf)bits+=b.toString(2).padStart(8,'0');for(let i=0;i<bits.length;i+=5)out+='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'[parseInt(bits.slice(i,i+5).padEnd(5,'0'),2)];return out}
async function getSetting(k, fallback=''){const r=await q('SELECT v FROM settings WHERE k=$1',[k]);return r[0]?.v ?? fallback}
async function setSetting(k,v){await exec('INSERT INTO settings(k,v) VALUES($1,$2) ON CONFLICT(k) DO UPDATE SET v=EXCLUDED.v',[k,String(v)])}
async function getKillSwitch(){return (await getSetting('kill_switch','false'))==='true'}
async function dailyGuard(equity){const d=new Date().toISOString().slice(0,10);let guardDate=await getSetting('guard_date',''),start=+(await getSetting('equity_start','0'));if(guardDate!==d){guardDate=d;start=equity;await setSetting('guard_date',d);await setSetting('equity_start',start);await setSetting('kill_switch','false')}if(!start&&equity>0){start=equity;await setSetting('equity_start',start)}const dd=start?Math.max(0,(start-equity)/start*100):0;if(dd>=MAX_DD)await setSetting('kill_switch','true');return {dd,equityStart:start}}
function ema(vals,n){if(vals.length<n)return null;let e=vals.slice(0,n).reduce((a,b)=>a+b,0)/n,k=2/(n+1);for(let i=n;i<vals.length;i++)e=vals[i]*k+e*(1-k);return e}
function srLevels(rows){const c=rows.slice(0,-1).map(x=>({o:+x[1],h:+x[2],l:+x[3],c:+x[4]})); if(c.length<40)return {support:null,resistance:null,context:'NO_LEVEL'}; const a=c.slice(-120),last=a.at(-1); const tr=[]; for(let i=2;i<a.length-2;i++){if(a[i].h>=a[i-1].h&&a[i].h>=a[i-2].h&&a[i].h>=a[i+1].h&&a[i].h>=a[i+2].h)tr.push(a[i].h);if(a[i].l<=a[i-1].l&&a[i].l<=a[i-2].l&&a[i].l<=a[i+1].l&&a[i].l<=a[i+2].l)tr.push(a[i].l)} const tol=last.c*.001; const levels=[]; for(const p of tr){let g=levels.find(x=>Math.abs(x.p-p)<=tol);if(!g){g={p,n:0};levels.push(g)}g.p=(g.p*g.n+p)/(g.n+1);g.n++} const sup=levels.filter(x=>x.p<last.c).sort((a,b)=>b.p-a.p)[0]?.p||null,res=levels.filter(x=>x.p>last.c).sort((a,b)=>a.p-b.p)[0]?.p||null; let context='BETWEEN_LEVELS'; if(sup&&last.l<sup&&last.c>sup)context='SUPPORT_REJECTION'; if(res&&last.h>res&&last.c<res)context='RESISTANCE_REJECTION'; return {support:sup,resistance:res,context,distanceSupport:sup?(last.c-sup)/last.c*100:null,distanceResistance:res?(res-last.c)/last.c*100:null}; }
function aiTrend(rows){if(!rows||rows.length<60)return {side:'WAIT',score:0,strength:'LOW',reason:['Menunggu minimal 60 candle']};const c=rows.map(x=>({o:+x[1],h:+x[2],l:+x[3],cl:+x[4]}));const closes=c.map(x=>x.cl),e9=ema(closes,9),e21=ema(closes,21),e50=ema(closes,50),e9p=ema(closes.slice(0,-1),9),e21p=ema(closes.slice(0,-1),21),recent=c.slice(-12),dirs=recent.slice(1).filter((x,i)=>x.cl>recent[i].cl).length,avgBody=recent.slice(0,-1).reduce((a,x)=>a+Math.abs(x.cl-x.o),0)/11,last=recent.at(-1),bull=dirs>=8&&e9>e21&&e21>e50&&e9>e9p&&e21>e21p, bear=(10-dirs)>=8&&e9<e21&&e21<e50&&e9<e9p&&e21<e21p;let bs=0,ss=0,r=[];if(e9>e21&&e9>e9p)bs+=25;if(e21>e50&&e21>e21p)bs+=20;if(dirs>=8)bs+=20;if(Math.abs(last.cl-last.o)>avgBody*1.25&&last.cl>last.o)bs+=10;if(last.h>=Math.max(...recent.slice(0,-1).map(x=>x.h)))bs+=15;if(e9<e21&&e9<e9p)ss+=25;if(e21<e50&&e21<e21p)ss+=20;if(dirs<=2)ss+=20;if(Math.abs(last.cl-last.o)>avgBody*1.25&&last.cl<last.o)ss+=10;if(last.l<=Math.min(...recent.slice(0,-1).map(x=>x.l)))ss+=15;if(bs>=60&&bs-ss>=15)r=['EMA 9/21/50 bullish','Mayoritas candle naik','Momentum/structure bullish'];else if(ss>=60&&ss-bs>=15)r=['EMA 9/21/50 bearish','Mayoritas candle turun','Momentum/structure bearish'];else r=['Trend belum cukup kuat','Menunggu konfirmasi candle berikutnya'];return {side:bs>=60&&bs-ss>=15?'BUY':ss>=60&&ss-bs>=15?'SELL':'WAIT',score:Math.max(bs,ss),strength:Math.max(bs,ss)>=75?'HIGH':Math.max(bs,ss)>=60?'MEDIUM':'LOW',reason:r,ema:{e9,e21,e50}}}
async function aiMulti(symbol){const tfs=[['4h',.30],['1h',.25],['15m',.20],['5m',.15],['1m',.10]],out=[];for(const [tf,w] of tfs){const rows=await binance('/fapi/v1/klines',{symbol,interval:tf,limit:150});const a=aiTrend(rows);out.push({timeframe:tf,weight:w,...a})}const buy=out.reduce((s,x)=>s+(x.side==='BUY'?x.weight:0),0),sell=out.reduce((s,x)=>s+(x.side==='SELL'?x.weight:0),0),buyN=out.filter(x=>x.side==='BUY').length,sellN=out.filter(x=>x.side==='SELL').length;let side='WAIT';if(buy>=.60&&buyN>=3)side='BUY';if(sell>=.60&&sellN>=3)side='SELL';return {symbol,side,score:Math.round(Math.max(buy,sell)*100),buyWeight:Math.round(buy*100),sellWeight:Math.round(sell*100),timeframes:out,updatedAt:Date.now()}}

app.get('/api/health',async(_,r)=>{try{await q('SELECT 1');r.json({ok:true,version:'5.6.0-vercel',live:LIVE,killSwitch:await getKillSwitch(),maxLeverage:MAXLEV,maxRiskPct:MAXRISK,dailyDrawdownPct:MAX_DD,db:'postgres'})}catch(e){r.status(503).json({ok:false,db:'down',error:e.message})}});
app.get('/api/auth/status',async(qr,r)=>{try{const u=(await q('SELECT username FROM users WHERE id=1'))[0];r.json({configured:!!u,authenticated:!!optionalAuth(qr),username:u?.username||null})}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/auth/setup',async(qr,r)=>{try{if((await q('SELECT id FROM users WHERE id=1')).length)throw Error('User already configured');const username=String(qr.body.username||'admin').trim(),password=String(qr.body.password||'');if(!username||password.length<12)throw Error('Username required and password must be at least 12 characters');const ph=passwordHash(password);await exec('INSERT INTO users(id,username,salt,password_hash,created_at) VALUES(1,$1,$2,$3,$4)',[username,ph.salt,ph.hash,Date.now()]);await audit('AUTH_SETUP',username);const token=makeToken(username);r.json({token,username,expiresInSec:SESSION_TTL/1000})}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/auth/login',async(qr,r)=>{try{const u=(await q('SELECT * FROM users WHERE id=1'))[0];if(!u)throw Error('Run setup first');const got=crypto.scryptSync(String(qr.body.password||''),u.salt,64,{N:16384,r:8,p:1});if(!crypto.timingSafeEqual(got,Buffer.from(u.password_hash,'hex')))throw Error('Invalid credentials');const row=(await q('SELECT totp_enc FROM credentials WHERE id=1'))[0];if(row?.totp_enc&&String(qr.body.code||'').trim()!==totp(dec(row.totp_enc)))throw Error('Valid 2FA code required');const token=makeToken(u.username);await audit('AUTH_LOGIN',u.username);r.json({token,username:u.username,expiresInSec:SESSION_TTL/1000})}catch(e){r.status(401).json({error:e.message})}});
app.post('/api/auth/logout',auth,(q,r)=>{r.json({ok:true})});
app.get('/api/klines',async(qr,r)=>{try{r.json(await binance('/fapi/v1/klines',{symbol:sym(qr.query.symbol),interval:qr.query.interval||'5m',limit:Math.min(+qr.query.limit||500,1500)}))}catch(e){r.status(400).json({error:e.message})}});
app.get('/api/ticker',async(qr,r)=>{try{r.json(await binance('/fapi/v2/ticker/price',{symbol:sym(qr.query.symbol)}))}catch(e){r.status(400).json({error:e.message})}});
app.get('/api/depth',async(qr,r)=>{try{r.json(await binance('/fapi/v1/depth',{symbol:sym(qr.query.symbol),limit:100}))}catch(e){r.status(400).json({error:e.message})}});
app.get('/api/open-interest',async(qr,r)=>{try{r.json(await binance('/fapi/v1/openInterest',{symbol:sym(qr.query.symbol)}))}catch(e){r.status(400).json({error:e.message})}});
app.get('/api/exchange-info',async(qr,r)=>{try{const all=await binance('/fapi/v1/exchangeInfo');const s=all.symbols.find(x=>x.symbol===sym(qr.query.symbol));if(!s)throw Error('Symbol not found');r.json(s)}catch(e){r.status(400).json({error:e.message})}});
app.get('/api/force-orders',async(qr,r)=>{try{r.json(await binance('/fapi/v1/forceOrders',{symbol:sym(qr.query.symbol),limit:20}))}catch(e){r.status(400).json({error:e.message})}});
app.get('/api/ai/trend',async(qr,r)=>{try{const symbol=sym(qr.query.symbol||'BTCUSDT'),rows=await binance('/fapi/v1/klines',{symbol,interval:qr.query.interval||'5m',limit:150});r.json({symbol,interval:qr.query.interval||'5m',...aiTrend(rows),updatedAt:Date.now()})}catch(e){r.status(400).json({error:e.message})}});
app.get('/api/ai/mtf',async(qr,r)=>{try{r.json(await aiMulti(sym(qr.query.symbol||'BTCUSDT')))}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/risk/check',async(qr,r)=>{try{r.json({...riskCalc(qr.body),killSwitch:await getKillSwitch()})}catch(e){r.status(400).json({error:e.message})}});
app.get('/api/account',async(_,r)=>{try{if(!LIVE){const positions=await q("SELECT * FROM trades WHERE status='OPEN' ORDER BY opened_at DESC LIMIT 200");return r.json({mode:'PAPER',balances:[],positions,killSwitch:await getKillSwitch()});}const [b,p]=await Promise.all([binance('/fapi/v3/balance',{},'GET',true),binance('/fapi/v3/positionRisk',{},'GET',true)]);const eq=+(b.find(x=>x.asset==='USDT')?.balance||0);r.json({mode:'LIVE',balances:b,positions:p,guard:await dailyGuard(eq),killSwitch:await getKillSwitch()})}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/kill-switch',auth,async(qr,r)=>{try{const enabled=!!qr.body.enabled;await setSetting('kill_switch',enabled);await audit('KILL_SWITCH',String(enabled),qr.user);if(enabled&&LIVE)await binance('/fapi/v1/allOpenOrders',{symbol:sym(qr.body.symbol||'BTCUSDT')},'DELETE',true);r.json({killSwitch:enabled})}catch(e){r.status(400).json({error:e.message})}});
app.get('/api/journal',async(_,r)=>{try{r.json(await q('SELECT * FROM trades ORDER BY opened_at DESC LIMIT 200'))}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/journal',auth,async(qr,r)=>{try{const b=qr.body,id=b.id||crypto.randomUUID();await exec(`INSERT INTO trades(id,symbol,side,entry,exit,qty,pnl,fee,funding,opened_at,closed_at,reason,setup,status,meta) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT(id) DO UPDATE SET exit=EXCLUDED.exit,pnl=EXCLUDED.pnl,status=EXCLUDED.status,closed_at=EXCLUDED.closed_at,meta=EXCLUDED.meta`,[id,b.symbol,b.side,+b.entry||0,+b.exit||0,+b.qty||0,+b.pnl||0,+b.fee||0,+b.funding||0,+b.openedAt||Date.now(),b.closedAt||null,b.reason||'',b.setup||'manual',b.status||'CLOSED',b.meta||{}]);await audit('JOURNAL_WRITE',id,qr.user);r.json({id})}catch(e){r.status(400).json({error:e.message})}});
app.get('/api/audit',async(_,r)=>{try{r.json(await q('SELECT * FROM audit ORDER BY created_at DESC LIMIT 300'))}catch(e){r.status(500).json({error:e.message})}});
app.get('/api/credentials/status',auth,async(_,r)=>{try{const row=(await q('SELECT api_key_enc,api_secret_enc,totp_enc FROM credentials WHERE id=1'))[0];r.json({configured:!!(row?.api_key_enc&&row?.api_secret_enc),twoFactorEnabled:!!row?.totp_enc})}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/credentials',auth,requireMaster,async(qr,r)=>{try{const apiKey=String(qr.body.apiKey||'').trim(),apiSecret=String(qr.body.apiSecret||'').trim();if(!apiKey||!apiSecret)throw Error('API Key and API Secret are required');if(apiKey.length<10||apiSecret.length<20)throw Error('Credential format looks invalid');const existing=(await q('SELECT totp_enc FROM credentials WHERE id=1'))[0];if(existing?.totp_enc&&String(qr.body.code||'').trim()!==totp(dec(existing.totp_enc)))throw Error('Valid 2FA code required');await exec(`INSERT INTO credentials(id,api_key_enc,api_secret_enc,totp_enc) VALUES(1,$1,$2,$3) ON CONFLICT(id) DO UPDATE SET api_key_enc=EXCLUDED.api_key_enc,api_secret_enc=EXCLUDED.api_secret_enc`,[enc(apiKey),enc(apiSecret),existing?.totp_enc||'']);await loadCredentials();await audit('CREDENTIALS_UPDATED','',qr.user);r.json({ok:true,configured:true})}catch(e){r.status(400).json({error:e.message})}});
app.delete('/api/credentials',auth,requireMaster,async(qr,r)=>{try{const existing=(await q('SELECT totp_enc FROM credentials WHERE id=1'))[0];if(existing?.totp_enc&&String(qr.body.code||'').trim()!==totp(dec(existing.totp_enc)))throw Error('Valid 2FA code required');await exec('DELETE FROM credentials WHERE id=1');KEY='';SECRET='';await audit('CREDENTIALS_REMOVED','',qr.user);r.json({ok:true})}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/2fa/setup',auth,requireMaster,async(qr,r)=>{try{const secret=base32(crypto.randomBytes(20)),row=(await q('SELECT api_key_enc,api_secret_enc FROM credentials WHERE id=1'))[0];await exec(`INSERT INTO credentials(id,api_key_enc,api_secret_enc,totp_enc) VALUES(1,$1,$2,$3) ON CONFLICT(id) DO UPDATE SET totp_enc=EXCLUDED.totp_enc`,[row?.api_key_enc||'',row?.api_secret_enc||'',enc(secret)]);await audit('2FA_SETUP','',qr.user);r.json({secret,otpauth:`otpauth://totp/Obsidian%20Futures?secret=${secret}&issuer=Obsidian`})}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/2fa/verify',auth,requireMaster,async(qr,r)=>{try{const row=(await q('SELECT totp_enc FROM credentials WHERE id=1'))[0];if(!row?.totp_enc)throw Error('2FA not configured');const secret=dec(row.totp_enc),code=String(qr.body.code||'').trim(),ok=[-1,0,1].some(d=>totp(secret,Math.floor(Date.now()/1000)+d*30)===code);if(ok)await audit('2FA_VERIFY','success',qr.user);r.json({ok})}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/paper/order',auth,async(qr,r)=>{try{if(await getKillSwitch())throw Error('Kill switch active');const b=qr.body,rc=riskCalc(b),id=crypto.randomUUID(),now=Date.now(),p={id,symbol:sym(b.symbol),side:b.side,entry:+b.entry,quantity:rc.quantity,sl:+b.stopLoss,tp:+b.takeProfit,openedAt:now,status:'OPEN',pnl:0};await exec(`INSERT INTO trades(id,symbol,side,entry,qty,opened_at,reason,setup,status,meta) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'OPEN',$9)`,[id,p.symbol,p.side,p.entry,p.quantity,now,b.reason||'manual',b.setup||'structure+ATR',b]);await audit('PAPER_ORDER',id,qr.user);r.json({mode:'PAPER',position:p,risk:rc})}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/live/order',auth,async(qr,r)=>{try{if(!LIVE)throw Error('Live trading disabled');if(await getKillSwitch())throw Error('Kill switch active');const b=qr.body,s=sym(b.symbol),rc=riskCalc(b),side=b.side==='LONG'?'BUY':'SELL';if(!b.stopLoss||!b.takeProfit)throw Error('SL/TP required');await binance('/fapi/v1/leverage',{symbol:s,leverage:rc.leverage},'POST',true);const info=await binance('/fapi/v1/exchangeInfo'),meta=info.symbols.find(x=>x.symbol===s);if(!meta)throw Error('Symbol unavailable');const lot=meta.filters.find(x=>x.filterType==='LOT_SIZE'),priceF=meta.filters.find(x=>x.filterType==='PRICE_FILTER'),step=+(lot?.stepSize||'0.001'),minQty=+(lot?.minQty||'0'),tick=+(priceF?.tickSize||'0.01'),round=(v,st)=>Math.floor(v/st+1e-10)*st,qty=round(rc.quantity,step),stop=round(+b.stopLoss,tick),take=round(+b.takeProfit,tick);if(qty<minQty)throw Error(`Quantity below exchange minimum ${minQty}`);const clientOrderId=`OBS-${Date.now()}-${crypto.randomBytes(3).toString('hex')}`,entry=await binance('/fapi/v1/order',{symbol:s,side,type:'MARKET',quantity:qty,newClientOrderId:clientOrderId,newOrderRespType:'RESULT'},'POST',true),exit=side==='BUY'?'SELL':'BUY',sl=await binance('/fapi/v1/algoOrder',{algoType:'CONDITIONAL',symbol:s,side:exit,type:'STOP_MARKET',triggerPrice:stop,closePosition:'true',workingType:'MARK_PRICE'},'POST',true),tp=await binance('/fapi/v1/algoOrder',{algoType:'CONDITIONAL',symbol:s,side:exit,type:'TAKE_PROFIT_MARKET',triggerPrice:take,closePosition:'true',workingType:'MARK_PRICE'},'POST',true);await audit('LIVE_ORDER',JSON.stringify({symbol:s,side,orderId:entry.orderId}),qr.user);r.json({mode:'LIVE',entry,sl,tp})}catch(e){r.status(400).json({error:e.message})}});

export default app;
